### PR TITLE
A test for pull request #718

### PR DESCRIPTION
**Pull request by josemduarte**
The test doesn't pass. An extra new line character appears in the uncompressed text.

### CODE REVIEW

**Comment by zweibieren** [comment]
The test fails. It says that the uncompressed stream has an additional newline. However, the code contains the "original text" as a constant, without a newline. But decompressing the test file with the unix "uncompress" command shows that the original test file did have a newline. A simple correction is to add the newline to the constant in the test program.

**Comment by josemduarte** [comment]
You are totally right, unix uncompress behaves in the same way and outputs a new line too. Perhaps the compress program added a new line? I'm not sure what happened exactly. My bad.

Could you add that new line and commit to your PR. After that we can merge. Thank you!

**Comment by zweibieren** [comment]
I'm also adding a longer test case.  half-an-hour or less
 

    On Thursday, January 25, 2018, 2:59:25 PM EST, Jose Manuel Duarte <notifications@github.com> wrote:  
 
 
You are totally right, unix uncompress behaves in the same way and outputs a new line too. Perhaps the compress program added a new line? I'm not sure what happened exactly. My bad.

Could you add that new line and commit to your PR. After that we can merge. Thank you!

**Comment by zweibieren** [comment]
I've added a pull request with the test fix and a bigger test. compress depends on file size
 

    On Thursday, January 25, 2018, 2:59:25 PM EST, Jose Manuel Duarte <notifications@github.com> wrote:  
 
 
You are totally right, unix uncompress behaves in the same way and outputs a new line too. Perhaps the compress program added a new line? I'm not sure what happened exactly. My bad.

Could you add that new line and commit to your PR. After that we can merge. Thank you!

**Pull request merged**
